### PR TITLE
hotfix - added missed import of FailEvent

### PR DESCRIPTION
**Pull request by Mitrichius**
Hotfix for #16: added import of Codeception\Event\FailEvent

### CODE REVIEW

**Comment by Mitrichius** [comment]
@vania-pooh, I'm so sorry for this...

**Comment by vania-pooh** [comment]
@Mitrichius do we need to recreate release?

**Comment by Mitrichius** [comment]
@vania-pooh yes

**Comment by vania-pooh** [comment]
@Mitrichius done.

**Pull request merged**
