### PR TITLE
Support Codeception 3.0

### PR DESCRIPTION
**Pull request by DavertMik**
Support latest Codeception

### CODE REVIEW

**Comment by DavertMik** [comment]
Please don't merge it for a while. I will check if there are more things that can be improved for compatibility.

**Comment by DavertMik** [comment]
Added support for attachments.
Ready to merge! :flight_departure:

**Comment by DavertMik** [comment]
@baev please! (and a release)

**Comment by baev** [comment]
@DavertMik thanks!

**Pull request merged**
